name: monstercount

on:
  schedule:
    # Daily Fenster 23:30–23:59 Europe/Berlin
    # Deckt Sommerzeit und Winterzeit ab
    - cron: "30-59/5 21 * * *"
    - cron: "30-59/5 22 * * *"

    # Homepage-Scan 10, 18, 21 Europe/Berlin
    - cron: "0 8 * * *"
    - cron: "0 16 * * *"
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: run tracker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python monstercount_tracker.py
      - name: commit updates
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state_monstercount.json members_bequiet.txt || true
          git commit -m "Update state and members" || echo "nichts zu committen"
          git push || true
