name: MonsterCount

on:
  schedule:
    # Sommerzeit Berlin ≈ 21:55 UTC
    - cron: "55 21 * * *"
    # Winterzeit Berlin ≈ 22:55 UTC
    - cron: "55 22 * * *"
  workflow_dispatch:

permissions:
  contents: write   # wir commiten die State-JSON ins Repo

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MonsterCount Tracker
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          # Optional: eigene Quelle für die Monstercount-Tabelle
          MONSTERCOUNT_URL: ${{ secrets.MONSTERCOUNT_URL }}
        run: |
          python monstercount_tracker.py

      - name: Commit state if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add monstercount_state.json || true
          if ! git diff --cached --quiet; then
            git commit -m "[skip ci] Update monstercount_state.json"
            git push
          fi
