name: Monstercount Tracker

on:
  workflow_dispatch:
  schedule:
    # Sommerzeitfenster Berlin 23:40–23:55 über 21:40–21:55 UTC
    - cron: '40-55 21 * * *'
    # Winterzeitfenster Berlin 23:40–23:55 über 22:40–22:55 UTC
    - cron: '40-55 22 * * *'

permissions:
  contents: read

concurrency:
  group: monstercount-tracker
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run tracker
        run: python monstercount_tracker.py
