name: MonsterCount

on:
  schedule:
    # Ein einziger Run pro Tag, um 22:55 UTC
    # Das Script selbst prüft, ob in Berlin 23:50–23:59 ist
    - cron: "55 22 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MonsterCount Tracker
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python monstercount_tracker.py
