name: monstercount-yearly
on:
  schedule:
    - cron: "*/5 22-23 31 12 *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python monstercount_tracker.py
      - run: |
          git config user.name "monstercount-bot"
          git config user.email "bot@example.com"
          git add -A
          git diff --cached --quiet || git commit -m "yearly rollup"
          git push
