name: Monstercount Tracker

on:
  schedule:
    - cron: "50 23 * * *"   # jeden Tag um 23:50 Uhr
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tracker
        run: python monstercount_tracker.py

      - name: Commit state files
        run: |
          git config user.name "bequiet-bot"
          git config user.email "bequiet-bot@example.com"
          git add data/
          git commit -m "Update state and daily snapshot" || echo "nothing to commit"
          git push
