name: monstercount

on:
  schedule:
    # Daily Fenster
    - cron: "41 21 * * *"   # 23:41 Berlin = 21:41 UTC im Winter abweichend, plane Puffer über mehrere Runs
    - cron: "46 21 * * *"
    - cron: "52 21 * * *"
    # Weekly Fenster am Sonntag
    - cron: "35 21 * * 0"
    - cron: "45 21 * * 0"
    # Monthly Fenster täglich, Skript postet nur am Monatsende
    - cron: "25 21 * * *"
    - cron: "45 21 * * *"
    # Homepage-Scan 10, 18, 21 Berlin
    - cron: "0 8 * * *"
    - cron: "0 16 * * *"
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: run tracker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python monstercount_tracker.py
      - name: commit updates
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state_monstercount.json members_bequiet.txt || true
          git commit -m "Update state and members" || echo "nichts zu committen"
          git push || true
