name: Monstercount Daily

on:
  schedule:
    # CEST Berlin 23:50 und 23:55  entspricht UTC 21:50 und 21:55
    - cron: "50 21 * * *"
    - cron: "55 21 * * *"
    # CET  Berlin 23:50 und 23:55  entspricht UTC 22:50 und 22:55
    - cron: "50 22 * * *"
    - cron: "55 22 * * *"
  workflow_dispatch:

# Läuft nur auf dem Default-Branch. Passe refs/heads/main an, falls dein Default anders heißt.
jobs:
  run-tracker:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    # Verhindert parallele Läufe, wenn GitHub verspätet triggert
    concurrency:
      group: monstercount-daily
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run tracker
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          # Optional. Der Job bleibt UTC, dein Skript nutzt ZoneInfo(Europe/Berlin).
          TZ: Europe/Berlin
        run: |
          python monstercount_tracker.py
