name: beQuiet Monstercount

on:
  schedule:
    # SOMMER (MESZ = UTC+2) → 23:40–23:55 DE = 21:40–21:55 UTC
    - cron: "40-55/5 21 * * *"
    # WINTER (MEZ = UTC+1) → 23:40–23:55 DE = 22:40–22:55 UTC
    - cron: "40-55/5 22 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: monstercount-tracker
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Monstercount tracker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_MONSTERCOUNT }}
          # TEST_MONSTERCOUNT: "true"      # <- zum Testen temporär einkommentieren
          # DEBUG_MONSTERCOUNT: "true"     # <- optional Debug
        run: python monstercount_tracker.py

      - name: Commit state (if changed)
        run: |
          if [ -f state_monstercount.json ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state_monstercount.json || true
            git diff --staged --quiet || git commit -m "Update monstercount state"
            git push
          fi
