name: Daily Monstercount

on:
  schedule:
    # ACHTUNG: GitHub Actions nutzt UTC.
    # 23:58 Uhr Europa/Berlin = 21:58 UTC (Sommerzeit). Im Winter (CET) = 22:58 UTC.
    - cron: "58 21 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monstercount tracker (with debug)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TEST_MONSTERCOUNT: "true"    # einmalig zum Testen: schickt eine Testzeile
          DEBUG_MONSTERCOUNT: "true"   # einmalig: schickt einen 🧪 DEBUG-Block mit Details
        run: |
          python monstercount_tracker.py
